[package]
name = "sparkle"
version = "0.1.0"
edition = "2024"

[dependencies]
file-format = "0.27.0"
clap = { version = "4.5.41", features = ["derive", "debug"] }
mime_guess2 = "2.3.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9"
